HoldTillRename: Rename knative-sandbox to knative-extension
knative/hack pull request #293
Opened 2023-05-24 08:18 UTC by davidhadas

This is an automated PR to replace `knative-sandbox` strings to `knative-extension`. Do not merge until productivity renames knative-sandbox org to knative-extension.

2023-05-25 20:08 UTC, davidhadas commented
Any reason why test does not pass?

2023-05-27 18:37 UTC, davidhadas commented
/retest

2023-07-18 10:14 UTC, dsimansk commented
/retest

2023-08-02 08:37 UTC, davidhadas commented on library.sh
> +  repoName="${repoName#knative-extension-}" # Remove knative-extension- prefix if any
```suggestion
  repoName="${repoName#knative-extensions-}" # Remove knative-extensions- prefix if any
```

2023-08-02 09:15 UTC, upodroid requested changes
It can replace knative-sandbox instead

2023-08-03 20:46 UTC, davidhadas commented on library.sh
>    repoName="${repoName#knative-sandbox-}" # Remove knative-sandbox- prefix if any
```suggestion
```

2023-08-03 22:01 UTC, upodroid approved these changes
LGTM

2023-08-03 22:02 UTC, merged